"""Multi-format import → book drafts: PDF, DOCX, EPUB, Markdown/TXT, JSON."""

import io
import json
import posixpath
import re
import zipfile
from html.parser import HTMLParser
from pathlib import PurePath
from xml.etree import ElementTree

SUPPORTED = {".pdf", ".docx", ".epub", ".md", ".markdown", ".txt", ".json"}
MAX_TEXT_CHARS = 2_000_000


class ImportErrorBadFile(ValueError):
    pass


def _as_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        value = re.split(r"[,;|]", value)
    return [str(v).strip() for v in value if str(v).strip()]


def _describe(text: str, limit: int = 420) -> str:
    """First sentences of the text, up to ~limit chars, as a fallback description."""
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    cut = flat[:limit]
    end = max(cut.rfind(". "), cut.rfind("! "), cut.rfind("? "))
    return (cut[:end + 1] if end > limit // 3 else cut.rstrip() + "…")


def normalize(raw: dict, source: str = "import") -> dict:
    """Map loose field names onto BookIn and validate. Raises ValueError when unusable."""
    if not isinstance(raw, dict):
        raise ValueError("each book must be a JSON object")
    title = str(raw.get("title") or "").strip()
    if not title:
        raise ValueError("a book is missing its title")
    text = str(raw.get("text") or raw.get("content") or raw.get("full_text") or "")[:MAX_TEXT_CHARS]
    description = str(raw.get("description") or raw.get("summary") or raw.get("short_description") or "").strip()
    return {
        "title": title[:300],
        "author": (str(raw.get("author") or raw.get("authors") or "").strip() or "Unknown")[:200],
        "description": (description or _describe(text) or "No description provided.")[:4000],
        "genres": _as_list(raw.get("genres") or raw.get("genre"))[:10],
        "themes": _as_list(raw.get("themes") or raw.get("tags") or raw.get("subjects"))[:20],
        "text": text,
        "source": source,
    }


# --- per-format extractors -------------------------------------------------

def _from_json(data: bytes) -> list[dict]:
    try:
        payload = json.loads(data.decode("utf-8-sig"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise ImportErrorBadFile(f"invalid JSON: {e}") from e
    if isinstance(payload, dict) and isinstance(payload.get("books"), list):
        payload = payload["books"]
    items = payload if isinstance(payload, list) else [payload]
    return [dict(item, source="json") if isinstance(item, dict) else item for item in items]


FRONT_MATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)


def _from_markdown(data: bytes, stem: str) -> list[dict]:
    text = data.decode("utf-8-sig", errors="replace")
    meta: dict = {}
    m = FRONT_MATTER.match(text)
    if m:
        for line in m.group(1).splitlines():
            key, sep, value = line.partition(":")
            if sep:
                meta[key.strip().lower()] = value.strip().strip("\"'").strip("[]")
        text = text[m.end():]
    heading = re.search(r"^#\s+(.+)$", text, re.M)
    by_line = re.search(r"^\s*(?:\*|_)?by\s+([^\n*_]+)", text, re.I | re.M)
    return [{**meta, "title": meta.get("title") or (heading.group(1).strip() if heading else stem),
             "author": meta.get("author") or (by_line.group(1).strip() if by_line else ""),
             "text": text.strip(), "source": "markdown"}]


def _from_pdf(data: bytes, stem: str) -> list[dict]:
    from pypdf import PdfReader
    from pypdf.errors import PdfReadError

    try:
        reader = PdfReader(io.BytesIO(data))
        text = "\n\n".join((page.extract_text() or "").strip() for page in reader.pages)
        info = reader.metadata or {}
    except (PdfReadError, ValueError, KeyError) as e:
        raise ImportErrorBadFile(f"unreadable PDF: {e}") from e
    if not text.strip():
        raise ImportErrorBadFile("the PDF has no extractable text (scanned images need OCR first)")
    return [{"title": (info.get("/Title") or "").strip() or stem, "author": (info.get("/Author") or "").strip(),
             "text": text, "source": "pdf"}]


def _from_docx(data: bytes, stem: str) -> list[dict]:
    import docx

    try:
        document = docx.Document(io.BytesIO(data))
    except Exception as e:  # python-docx raises several unrelated types for corrupt files
        raise ImportErrorBadFile(f"unreadable DOCX: {e}") from e
    props = document.core_properties
    text = "\n\n".join(p.text.strip() for p in document.paragraphs if p.text.strip())
    return [{"title": (props.title or "").strip() or stem, "author": (props.author or "").strip(),
             # core "comments" is often tool boilerplate ("generated by …"), so only subject is trusted
             "description": (props.subject or "").strip(), "themes": props.keywords or "",
             "text": text, "source": "docx"}]


class _TextExtractor(HTMLParser):
    BLOCK = {"p", "div", "br", "h1", "h2", "h3", "h4", "h5", "h6", "li", "section", "blockquote", "tr"}
    SKIP = {"script", "style", "head", "title"}

    def __init__(self):
        super().__init__()
        self.parts: list[str] = []
        self.skip = 0

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self.skip += 1
        elif tag in self.BLOCK:
            self.parts.append("\n\n")

    def handle_endtag(self, tag):
        if tag in self.SKIP and self.skip:
            self.skip -= 1

    def handle_data(self, data):
        if not self.skip:
            self.parts.append(data)


def html_to_text(html: str) -> str:
    parser = _TextExtractor()
    parser.feed(html)
    text = "".join(parser.parts)
    return "\n\n".join(" ".join(p.split()) for p in text.split("\n\n") if p.strip())


def _from_epub(data: bytes, stem: str) -> list[dict]:
    ns = {"c": "urn:oasis:names:tc:opendocument:xmlns:container", "opf": "http://www.idpf.org/2007/opf",
          "dc": "http://purl.org/dc/elements/1.1/"}
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as z:
            container = ElementTree.fromstring(z.read("META-INF/container.xml"))
            opf_path = container.find(".//c:rootfile", ns).attrib["full-path"]
            opf = ElementTree.fromstring(z.read(opf_path))
            base = posixpath.dirname(opf_path)

            def dc(tag: str) -> list[str]:
                return [(el.text or "").strip() for el in opf.findall(f".//dc:{tag}", ns) if (el.text or "").strip()]

            manifest = {item.attrib["id"]: item.attrib["href"] for item in opf.findall(".//opf:manifest/opf:item", ns)}
            chapters = []
            for ref in opf.findall(".//opf:spine/opf:itemref", ns):
                href = manifest.get(ref.attrib.get("idref", ""))
                if href:
                    name = posixpath.normpath(posixpath.join(base, href))
                    chapters.append(html_to_text(z.read(name).decode("utf-8", errors="replace")))
    except (zipfile.BadZipFile, KeyError, AttributeError, ElementTree.ParseError) as e:
        raise ImportErrorBadFile(f"unreadable EPUB: {e}") from e
    description = html_to_text(" ".join(dc("description")))
    return [{"title": (dc("title") or [stem])[0], "author": ", ".join(dc("creator")), "description": description,
             "themes": dc("subject"), "text": "\n\n".join(c for c in chapters if c), "source": "epub"}]


def parse_upload(filename: str, data: bytes) -> list[dict]:
    """Returns normalized drafts. Raises ImportErrorBadFile for unsupported or unreadable files."""
    path = PurePath(filename or "upload")
    ext, stem = path.suffix.lower(), path.stem.replace("_", " ").strip() or "Untitled"
    if ext not in SUPPORTED:
        raise ImportErrorBadFile(f"unsupported file type '{ext or '?'}' — use PDF, DOCX, EPUB, Markdown, TXT or JSON")
    if not data:
        raise ImportErrorBadFile("the file is empty")
    raw = {".json": lambda: _from_json(data), ".pdf": lambda: _from_pdf(data, stem),
           ".docx": lambda: _from_docx(data, stem), ".epub": lambda: _from_epub(data, stem)
           }.get(ext, lambda: _from_markdown(data, stem))()
    drafts, errors = [], []
    for item in raw:
        try:
            drafts.append(normalize(item, item.get("source", "import") if isinstance(item, dict) else "import"))
        except ValueError as e:
            errors.append(str(e))
    if not drafts:
        raise ImportErrorBadFile("; ".join(errors) or "no books found in the file")
    return drafts
